<?php
$z[0]=Array("item","",4,108);
$z[0][4]['name']="图片管理";
$z[0][4]['link']="media_main.php?dopost=filemanager";
$z[0][4]['rank']="plus_文件管理器";
$z[0][4]['target']="main";
$z[1]=Array("item","",112,183);
$z[1][4]['name']="上传新文件";
$z[1][4]['link']="media_add.php";
$z[1][4]['rank']="";
$z[1][4]['target']="main";
$z[2]=Array("item","",187,284);
$z[2][4]['name']="附件数据管理";
$z[2][4]['link']="media_main.php";
$z[2][4]['rank']="sys_Upload,sys_MyUpload";
$z[2][4]['target']="main";

?>