
  <m:item name='网站栏目' link='catalog_main.php' ischannel='1' addalt='创建栏目' linkadd='catalog_add.php?listtype=all' rank='t_List,t_AccList' target='main' />
  <m:item name='重复检测' link='article_test_same.php' rank='sys_ArcBatch' target='main' />
  <m:item name='自动摘要' link='article_description_main.php' rank='sys_Keyword' target='main' />
  <m:item name='回收站' link='recycling.php' ischannel='1' addalt='清空回收站' addico='images/gtk-del.gif' linkadd='archives_do.php?dopost=clear&aid=no&recycle=1' rank='a_List,a_AccList,a_MyList' target='main' />
