<?php
$z[0]=Array("arcurl","",93,108);
$z[1]=Array("litpic","",120,135);
$z[2]=Array("title","",190,204);
$z[3]=Array("title","",213,227);
$z[4]=Array("arcurl","",335,350);
$z[5]=Array("title","",359,373);
$z[6]=Array("title","",375,389);
$z[7]=Array("typeurl","",459,475);
$z[8]=Array("typename","",477,494);
$z[9]=Array("pubdate","",534,586);
$z[9][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[10]=Array("writer","",632,647);
$z[11]=Array("info","",773,786);
$z[12]=Array("info","",910,923);

?>