<div id="box_left_div">
            	<div id="box_left_div_img">
                	<a href="[field:arcurl/]"><img src="[field:litpic/]" onerror="this.src='../images/cloudcms_img.jpg'" alt="[field:title/]" title="[field:title/]"></a>
                </div>
                <div id="box_left_div_info">
                	<h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
                    <ul>
                    	<i><a href="[field:typeurl/]">[field:typename/]</a></i>
                        <i><a>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</a></i>
                        <i><a>×÷Õß£º[field:writer/]</a></i>
                    </ul>
                    <ul class="box_left_div_info_ul_phone">
                    	<li><a>[field:info/]</a></li>
                    </ul>
                    <ul class="box_left_div_info_ul_pc">
                    	<li><a>[field:info/]</a></li>
                    </ul>
                </div>
            </div>