
  <m:item name='系统基本参数' link='sys_info.php' rank='sys_Edit' target='main' />
  <m:item name='文件式管理器' link='file_manage_main.php' rank='sys_Edit' target='main' />
  <m:item name='友情链接管理' link='friendlink_main.php' rank='sys_Edit' target='main' />
  <m:item name='图片水印设置' link='sys_info_mark.php' rank='sys_Edit' target='main' />
  <m:item name='自定义表单' link='diy_main.php' rank='c_List' target='main' />
