<?php
$z[0]=Array("type","<a title=\"[field:typename/]\">[field:typename/]</a>",94,178);
$z[0][4]['typeid']="3";
$z[1]=Array("arclist","\r\n                	<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",260,435);
$z[1][4]['typeid']="3";
$z[1][4]['row']="5";
$z[1][4]['titlelen']="36";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",725,752);
$z[2][4]['name']="phpurl";
$z[3]=Array("arclist","\r\n                	<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",1394,1569);
$z[3][4]['typeid']="1,2";
$z[3][4]['row']="5";
$z[3][4]['titlelen']="36";
$z[3][4]['orderby']="click";
$z[4]=Array("arclist","\r\n                	<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",1807,1995);
$z[4][4]['typeid']="1,2,3";
$z[4][4]['row']="5";
$z[4][4]['titlelen']="36";
$z[4][4]['flag']="c";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("flink","",2289,2310);
$z[5][4]['row']="8";
$z[6]=Array("global","",2718,2745);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",2849,2876);
$z[7][4]['name']="cfg_basehost";

?>