<?php
$z[0]=Array("global","",36,63);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",161,188);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",228,258);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",911,936);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",968,995);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1346,1371);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",1434,1543);
$z[6][4]['typeid']="1";
$z[7]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",1574,1683);
$z[7][4]['typeid']="2";
$z[8]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",1714,1823);
$z[8][4]['typeid']="3";
$z[9]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",1854,1963);
$z[9][4]['typeid']="4";
$z[10]=Array("global","",2149,2174);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("global","",2206,2233);
$z[11][4]['name']="cfg_basehost";
$z[12]=Array("global","",2404,2429);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",2475,2584);
$z[13][4]['typeid']="1";
$z[14]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",2607,2716);
$z[14][4]['typeid']="2";
$z[15]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",2739,2848);
$z[15][4]['typeid']="3";
$z[16]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",2871,2980);
$z[16][4]['typeid']="4";

?>